name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install marge-cli (caso não esteja no package.json)
        run: npm install -g marge-cli

      - name: Run Cypress tests
        run: npx cypress run

      - name: List report files for debugging
        run: ls -la cypress/reports/ || true

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge "cypress/reports/*.json" > cypress/reports/report.json

      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/report.json --reportDir cypress/reports/html

      - name: Verify HTML report directory
        run: |
          if [ ! -d "cypress/reports/html" ]; then
            echo "Directory does not exist."
            exit 1
          fi
          if [ -z "$(ls -A cypress/reports/html)" ]; then
            echo "Directory is empty."
            exit 1
          fi

      - name: List generated HTML report files for debugging
        run: ls -la cypress/reports/html

      - name: Upload Mochawesome HTML report artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/html
