name: Cypress Tests with Report Publishing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Clean previous mochawesome HTML reports
        run: rm -rf cypress/reports/*

      - name: Generate mochawesome report (merge + html)
        run: |
          npx mochawesome-merge "cypress/reports/*.json" > cypress/reports/report.json
          npx marge cypress/reports/report.json --reportDir cypress/reports --overwrite

      - name: Publish Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
